import { MetricDefinition, FranchiseInfo, ResultGrain, CustodyScope } from "./types";

export const CANONICAL_FRANCHISES: FranchiseInfo[] = [
  // 12 Active 2026 Field Franchises
  {
    franchise_id: "FRAN_SVS",
    display_name: "Squaw Valley Skinners",
    owner_id: "OWNER_SVS",
    owner_display_name: "Chris Zweifel",
    canonical_name: "Squaw Valley Skinners",
    current_logo_path: "/logos/squaw-valley-skinners.jpg",
    primary_color: "#ff6a00",
    secondary_color: "#00a2ff",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_DCMC",
    display_name: "DC Mighty Cucks",
    owner_id: "OWNER_DCMC",
    owner_display_name: "Austin Williams",
    canonical_name: "DC Mighty Cucks",
    current_logo_path: "/logos/dc-mighty-cucks.png",
    primary_color: "#e02424",
    secondary_color: "#3f83f8",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_GGG",
    display_name: "Goleta Gringos",
    owner_id: "OWNER_GGG",
    owner_display_name: "Kevin Sliger",
    canonical_name: "Goleta Gringos",
    current_logo_path: "/logos/goleta-gringos.jpg",
    primary_color: "#00a2ff",
    secondary_color: "#c8ff00",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_GTF",
    display_name: "Grand Teeton Feelers",
    owner_id: "OWNER_GTF",
    owner_display_name: "Ryan Childress",
    canonical_name: "Grand Teeton Feelers",
    current_logo_path: "/logos/grand-teeton-feelers.jpg",
    primary_color: "#c8ff00",
    secondary_color: "#00a2ff",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_WWL",
    display_name: "Westeros Warlords",
    owner_id: "OWNER_WWL",
    owner_display_name: "Levi Sanchez",
    canonical_name: "Westeros Warlords",
    current_logo_path: "/logos/westeros-warlords.png",
    primary_color: "#d97706",
    secondary_color: "#4b5563",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_TJS",
    display_name: "Tijuana Sanchitos",
    owner_id: "OWNER_TJS",
    owner_display_name: "Zack Blotz",
    canonical_name: "Tijuana Sanchitos",
    current_logo_path: "/logos/tijuana-sanchitos.svg",
    primary_color: "#10b981",
    secondary_color: "#f59e0b",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_HLH",
    display_name: "Honolulu Horndogs",
    owner_id: "OWNER_HLH",
    owner_display_name: "Alex Clausen",
    canonical_name: "Honolulu Horndogs",
    current_logo_path: "/logos/honolulu-horndogs.png",
    primary_color: "#8b5cf6",
    secondary_color: "#38bdf8",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_FFC",
    display_name: "Fairview Fat Cats",
    owner_id: "OWNER_FFC",
    owner_display_name: "Alex Renney",
    canonical_name: "Fairview Fat Cats",
    current_logo_path: "/logos/fairview-fat-cats.png",
    primary_color: "#ffc400",
    secondary_color: "#1c2536",
    first_season: 2015,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_SDS",
    display_name: "San Diego Shadowcöcks",
    owner_id: "OWNER_SDS",
    owner_display_name: "John Newton",
    canonical_name: "San Diego Shadowcöcks",
    current_logo_path: "/logos/san-diego-shadowcocks.jpg",
    primary_color: "#7928ca",
    secondary_color: "#ff0080",
    first_season: 2019,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_PTP",
    display_name: "Patagonia Pipers",
    owner_id: "OWNER_PTP",
    owner_display_name: "Patrick O'Neill",
    canonical_name: "Patagonia Pipers",
    current_logo_path: "/logos/patagonia-pipers.png",
    primary_color: "#06b6d4",
    secondary_color: "#ec4899",
    first_season: 2024,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_COG",
    display_name: "Central Oregon Gabagooners",
    owner_id: "OWNER_COG",
    owner_display_name: "Andy Pietromonaco",
    canonical_name: "Central Oregon Gabagooners",
    current_logo_path: "/logos/central-oregon-gabagooners.jpg",
    primary_color: "#ec4899",
    secondary_color: "#f97316",
    first_season: 2026,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_CVC",
    display_name: "Chula Vista Chupacabras",
    owner_id: "OWNER_CVC",
    owner_display_name: "Jason Kafka",
    canonical_name: "Chula Vista Chupacabras",
    current_logo_path: "/logos/chula-vista-chupacabras.jpg",
    primary_color: "#14b8a6",
    secondary_color: "#6366f1",
    first_season: 2016,
    last_season: 2023,
    is_active: 0,
  },

  // Historical / Alumni Franchises
  {
    franchise_id: "FRAN_MCMD",
    display_name: "Muck City Mad Dawgs",
    owner_id: "OWNER_MCMD",
    owner_display_name: "Garrett Jones",
    canonical_name: "Muck City Mad Dawgs",
    current_logo_path: "/logos/muck-city-mad-dawgs.jpg",
    primary_color: "#0284c7",
    secondary_color: "#0ea5e9",
    first_season: 2014,
    last_season: 2020,
    is_active: 0,
  },
  {
    franchise_id: "FRAN_PND",
    display_name: "Pasco Pounders",
    owner_id: "OWNER_PND",
    owner_display_name: "Tyler Sanchez",
    canonical_name: "Pasco Pounders",
    current_logo_path: "/logos/pasco-pounders.png",
    primary_color: "#64748b",
    secondary_color: "#94a3b8",
    first_season: 2021,
    last_season: 2025,
    is_active: 0,
  },
  {
    franchise_id: "FRAN_PLW",
    display_name: "Poulsbo Pollywogs",
    owner_id: "OWNER_PLW",
    owner_display_name: "Steven Breitmayer",
    canonical_name: "Poulsbo Pollywogs",
    current_logo_path: "/logos/poulsbo-pollywogs.jpg",
    primary_color: "#22c55e",
    secondary_color: "#15803d",
    first_season: 2021,
    last_season: 2025,
    is_active: 0,
  },
  {
    franchise_id: "FRAN_WSW",
    display_name: "Winston-Salem Wake Snakes",
    owner_id: "OWNER_WSW",
    owner_display_name: "Tanner Dunn",
    canonical_name: "Winston-Salem Wake Snakes",
    current_logo_path: "/logos/winston-salem-wake-snakes.jpg",
    primary_color: "#f97316",
    secondary_color: "#ea580c",
    first_season: 2017,
    last_season: 2020,
    is_active: 0,
  },
  {
    franchise_id: "FRAN_CCB",
    display_name: "Charleston Chewbacca",
    owner_id: "OWNER_CCB",
    owner_display_name: "Jake Hibbard",
    canonical_name: "Charleston Chewbacca",
    current_logo_path: "/logos/warlords.svg",
    primary_color: "#9333ea",
    secondary_color: "#7e22ce",
    first_season: 2015,
    last_season: 2018,
    is_active: 0,
  },
  {
    franchise_id: "FRAN_PWP",
    display_name: "Pawtucket Patriots",
    owner_id: "OWNER_PWP",
    owner_display_name: "Scott Ace",
    canonical_name: "Pawtucket Patriots",
    current_logo_path: "/logos/pawtucket-patriots.gif",
    primary_color: "#3b82f6",
    secondary_color: "#1d4ed8",
    first_season: 2014,
    last_season: 2014,
    is_active: 0,
  },
  {
    franchise_id: "FRAN_LOB",
    display_name: "L.O.B. Thunder",
    owner_id: "OWNER_LOB",
    owner_display_name: "David Allardyce",
    canonical_name: "L.O.B. Thunder",
    current_logo_path: "/logos/lob-thunder.jpg",
    primary_color: "#14b8a6",
    secondary_color: "#0f766e",
    first_season: 2014,
    last_season: 2014,
    is_active: 0,
  },
];

export const GRAINS: { id: ResultGrain; label: string; description: string }[] = [
  { id: "player", label: "Player", description: "Aggregated by individual player" },
  { id: "franchise", label: "AFFL Franchise", description: "Aggregated by durable AFFL franchise" },
  { id: "team_season", label: "AFFL Team-Season", description: "Aggregated by specific historical team season" },
  { id: "nfl_team", label: "NFL Team", description: "Aggregated by pro football club" },
  { id: "position", label: "Position", description: "Aggregated by roster position (QB, RB, WR, TE, etc.)" },
  { id: "season", label: "Season", description: "Aggregated by NFL / AFFL competition year" },
  { id: "week", label: "Week", description: "Aggregated by specific matchup week" },
  { id: "game", label: "Game", description: "Aggregated by individual NFL game contest" },
  { id: "play", label: "Play", description: "Individual NFL play-level event grain" },
];

export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  affl_points: {
    id: "affl_points",
    name: "AFFL Fantasy Points",
    shortName: "AFFL Pts",
    category: "fantasy",
    description: "Standard non-PPR fantasy points scored in the AFFL.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? v.toFixed(1) : "—"),
  },
  bench_points: {
    id: "bench_points",
    name: "Bench Points Left",
    shortName: "Bench Pts",
    category: "fantasy",
    description: "Fantasy points scored while occupying an AFFL bench or inactive slot.",
    compatibleGrains: ["player", "franchise", "team_season", "position", "season", "week"],
    format: (v) => (v != null ? v.toFixed(1) : "—"),
  },
  xfp: {
    id: "xfp",
    name: "Expected Fantasy Points (xFP)",
    shortName: "xFP",
    category: "opportunity",
    description: "Expected standard non-PPR fantasy points based on down, distance, yardline, and air yards.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game", "play"],
    format: (v) => (v != null ? v.toFixed(1) : "—"),
  },
  fpoe: {
    id: "fpoe",
    name: "Fantasy Points Over Expected (FPOE)",
    shortName: "FPOE",
    category: "efficiency",
    description: "Actual AFFL fantasy points minus Expected Fantasy Points (xFP).",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? (v > 0 ? `+${v.toFixed(1)}` : v.toFixed(1)) : "—"),
  },
  custody_par: {
    id: "custody_par",
    name: "Custody Points Above Replacement (PAR)",
    shortName: "Custody PAR",
    category: "fantasy",
    description: "Fantasy points delivered above positional replacement level during active custody.",
    compatibleGrains: ["player", "franchise", "team_season", "position", "season"],
    format: (v) => (v != null ? (v > 0 ? `+${v.toFixed(1)}` : v.toFixed(1)) : "—"),
  },
  wopr: {
    id: "wopr",
    name: "Weighted Opportunity Rating (WOPR)",
    shortName: "WOPR",
    category: "opportunity",
    description: "1.5 * Target Share + 0.7 * Air Yards Share",
    compatibleGrains: ["player", "position", "season", "week"],
    format: (v) => (v != null ? v.toFixed(3) : "—"),
  },
  targets: {
    id: "targets",
    name: "Targets",
    shortName: "Tgt",
    category: "volume",
    description: "Total passing targets directed at player.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  receptions: {
    id: "receptions",
    name: "Receptions",
    shortName: "Rec",
    category: "volume",
    description: "Total completed passes caught.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rec_yds: {
    id: "rec_yds",
    name: "Receiving Yards",
    shortName: "Rec Yds",
    category: "volume",
    description: "Total receiving yardage gained.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rec_td: {
    id: "rec_td",
    name: "Receiving Touchdowns",
    shortName: "Rec TD",
    category: "volume",
    description: "Total receiving touchdowns scored.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rush_att: {
    id: "rush_att",
    name: "Rushing Attempts",
    shortName: "Carries",
    category: "volume",
    description: "Total rushing carries.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rush_yds: {
    id: "rush_yds",
    name: "Rushing Yards",
    shortName: "Rush Yds",
    category: "volume",
    description: "Total rushing yards gained.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rush_td: {
    id: "rush_td",
    name: "Rushing Touchdowns",
    shortName: "Rush TD",
    category: "volume",
    description: "Total rushing touchdowns scored.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  pass_yds: {
    id: "pass_yds",
    name: "Passing Yards",
    shortName: "Pass Yds",
    category: "volume",
    description: "Total passing yards gained.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  pass_td: {
    id: "pass_td",
    name: "Passing Touchdowns",
    shortName: "Pass TD",
    category: "volume",
    description: "Total passing touchdowns thrown.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  epa: {
    id: "epa",
    name: "Expected Points Added (EPA)",
    shortName: "EPA",
    category: "efficiency",
    description: "Total Expected Points Added generated on plays involving the player.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game", "play"],
    format: (v) => (v != null ? (v > 0 ? `+${v.toFixed(1)}` : v.toFixed(1)) : "—"),
  },
  target_share: {
    id: "target_share",
    name: "Target Share %",
    shortName: "Tgt %",
    category: "opportunity",
    description: "Percentage of team passing targets directed at player.",
    compatibleGrains: ["player", "position", "season", "week"],
    format: (v) => (v != null ? `${(v * 100).toFixed(1)}%` : "—"),
  },
  air_yards_share: {
    id: "air_yards_share",
    name: "Air Yards Share %",
    shortName: "AY %",
    category: "opportunity",
    description: "Percentage of team total passing air yards thrown to player.",
    compatibleGrains: ["player", "position", "season", "week"],
    format: (v) => (v != null ? `${(v * 100).toFixed(1)}%` : "—"),
  },
  air_yards: {
    id: "air_yards",
    name: "Total Air Yards",
    shortName: "Air Yds",
    category: "opportunity",
    description: "Total distance thrown past the line of scrimmage.",
    compatibleGrains: ["player", "position", "season", "week"],
    format: (v) => (v != null ? Math.round(v).toLocaleString() : "—"),
  },
  yac: {
    id: "yac",
    name: "Yards After Catch (YAC)",
    shortName: "YAC",
    category: "efficiency",
    description: "Yards gained after catching the ball.",
    compatibleGrains: ["player", "position", "season", "week"],
    format: (v) => (v != null ? Math.round(v).toLocaleString() : "—"),
  },
};

export const EXPLORE_PRESETS = [
  {
    id: "workload_left_on_bench",
    title: "Workload Left on the Bench",
    description: "Which workload spikes and scoring outbursts occurred while sitting on AFFL benches?",
    state: {
      scope: "rostered" as CustodyScope,
      grain: "player" as ResultGrain,
      metrics: ["bench_points", "affl_points", "xfp", "fpoe", "rush_yds", "rec_yds"],
      startSeason: 2018,
      endSeason: 2025,
      sortBy: "bench_points",
      sortDir: "desc" as const,
      limit: 50,
    },
  },
  {
    id: "talent_held_vs_started",
    title: "Talent Held vs. Talent Started",
    description: "Which franchises accumulated the most talent versus which ones maximized starting lineups?",
    state: {
      scope: "rostered" as CustodyScope,
      grain: "franchise" as ResultGrain,
      metrics: ["affl_points", "bench_points", "custody_par", "xfp", "fpoe"],
      startSeason: 2018,
      endSeason: 2025,
      sortBy: "affl_points",
      sortDir: "desc" as const,
      limit: 20,
    },
  },
  {
    id: "opportunity_vs_realized",
    title: "Opportunity Owned vs. Points Realized",
    description: "Comparison of expected standard non-PPR points (xFP) to actual AFFL points scored under custody.",
    state: {
      scope: "rostered" as CustodyScope,
      grain: "player" as ResultGrain,
      metrics: ["affl_points", "xfp", "fpoe", "targets", "rush_att"],
      startSeason: 2014,
      endSeason: 2025,
      sortBy: "xfp",
      sortDir: "desc" as const,
      limit: 50,
    },
  },
  {
    id: "redzone_by_franchise",
    title: "Red-Zone Opportunity by AFFL Franchise",
    description: "High-value goal-line and red-zone opportunities held across franchise histories.",
    state: {
      scope: "started" as CustodyScope,
      grain: "franchise" as ResultGrain,
      metrics: ["affl_points", "rush_td", "rec_td", "xfp", "fpoe"],
      startSeason: 2014,
      endSeason: 2025,
      sortBy: "rec_td",
      sortDir: "desc" as const,
      limit: 20,
    },
  },
  {
    id: "explosive_plays_under_custody",
    title: "Explosive Plays Under Custody",
    description: "Longest runs, deep passes, and game-breaking plays generated while in AFFL lineups.",
    state: {
      scope: "started" as CustodyScope,
      grain: "player" as ResultGrain,
      metrics: ["affl_points", "rec_yds", "rush_yds", "pass_yds", "epa"],
      startSeason: 2014,
      endSeason: 2025,
      sortBy: "affl_points",
      sortDir: "desc" as const,
      limit: 50,
    },
  },
];
