import { MetricDefinition, FranchiseInfo, ResultGrain, CustodyScope } from "./types";

export const CANONICAL_FRANCHISES: FranchiseInfo[] = [
  {
    franchise_id: "FRAN_SVS",
    display_name: "Squaw Valley Skinners",
    owner_id: "OWNER_SVS",
    owner_display_name: "Squaw Valley Skinners Owner",
    canonical_name: "Squaw Valley Skinners",
    current_logo_path: "/assets/logos/skinners.svg",
    primary_color: "#ff6a00",
    secondary_color: "#00a2ff",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_FFC",
    display_name: "Fairview Fat Cats",
    owner_id: "OWNER_FFC",
    owner_display_name: "Fairview Fat Cats Owner",
    canonical_name: "Fairview Fat Cats",
    current_logo_path: "/assets/logos/fatcats.svg",
    primary_color: "#ffc400",
    secondary_color: "#1c2536",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_GGG",
    display_name: "Goleta Gringos",
    owner_id: "OWNER_GGG",
    owner_display_name: "Goleta Gringos Owner",
    canonical_name: "Goleta Gringos",
    current_logo_path: "/assets/logos/gringos.svg",
    primary_color: "#00a2ff",
    secondary_color: "#c8ff00",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_SDS",
    display_name: "San Diego Shadowcöcks",
    owner_id: "OWNER_SDS",
    owner_display_name: "San Diego Shadowcöcks Owner",
    canonical_name: "San Diego Shadowcöcks",
    current_logo_path: "/assets/logos/shadowcocks.svg",
    primary_color: "#7928ca",
    secondary_color: "#ff0080",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_DCMC",
    display_name: "DC Mighty Cucks",
    owner_id: "OWNER_DCMC",
    owner_display_name: "DC Mighty Cucks Owner",
    canonical_name: "DC Mighty Cucks",
    current_logo_path: "/assets/logos/cucks.svg",
    primary_color: "#e02424",
    secondary_color: "#3f83f8",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_GTF",
    display_name: "Grand Teeton Feelers",
    owner_id: "OWNER_GTF",
    owner_display_name: "Grand Teeton Feelers Owner",
    canonical_name: "Grand Teeton Feelers",
    current_logo_path: "/assets/logos/feelers.svg",
    primary_color: "#c8ff00",
    secondary_color: "#00a2ff",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_WWL",
    display_name: "Westeros Warlords",
    owner_id: "OWNER_WWL",
    owner_display_name: "Westeros Warlords Owner",
    canonical_name: "Westeros Warlords",
    current_logo_path: "/assets/logos/warlords.svg",
    primary_color: "#d97706",
    secondary_color: "#4b5563",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_TJS",
    display_name: "Tijuana Sanchitos",
    owner_id: "OWNER_TJS",
    owner_display_name: "Tijuana Sanchitos Owner",
    canonical_name: "Tijuana Sanchitos",
    current_logo_path: "/assets/logos/sanchitos.svg",
    primary_color: "#10b981",
    secondary_color: "#f59e0b",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_PTP",
    display_name: "Patagonia Pipers",
    owner_id: "OWNER_PTP",
    owner_display_name: "Patagonia Pipers Owner",
    canonical_name: "Patagonia Pipers",
    current_logo_path: "/assets/logos/pipers.svg",
    primary_color: "#06b6d4",
    secondary_color: "#ec4899",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_HLH",
    display_name: "Honolulu Horndogs",
    owner_id: "OWNER_HLH",
    owner_display_name: "Honolulu Horndogs Owner",
    canonical_name: "Honolulu Horndogs",
    current_logo_path: "/assets/logos/horndogs.svg",
    primary_color: "#8b5cf6",
    secondary_color: "#38bdf8",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_COG",
    display_name: "Central Oregon Gabagooners",
    owner_id: "OWNER_COG",
    owner_display_name: "Central Oregon Gabagooners Owner",
    canonical_name: "Central Oregon Gabagooners",
    current_logo_path: "/assets/logos/gabagooners.svg",
    primary_color: "#ec4899",
    secondary_color: "#f97316",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_CVC",
    display_name: "Chula Vista Chupacabras",
    owner_id: "OWNER_CVC",
    owner_display_name: "Chula Vista Chupacabras Owner",
    canonical_name: "Chula Vista Chupacabras",
    current_logo_path: "/assets/logos/chupacabras.svg",
    primary_color: "#14b8a6",
    secondary_color: "#6366f1",
    first_season: 2014,
    last_season: 2026,
    is_active: 1,
  },
  {
    franchise_id: "FRAN_PND",
    display_name: "Pasco Pounders",
    owner_id: "OWNER_PND",
    owner_display_name: "Pasco Pounders Owner",
    canonical_name: "Pasco Pounders",
    current_logo_path: "/assets/logos/pounders.svg",
    primary_color: "#64748b",
    secondary_color: "#94a3b8",
    first_season: 2014,
    last_season: 2020,
    is_active: 0,
  },
  {
    franchise_id: "FRAN_PLW",
    display_name: "Poulsbo Pollywogs",
    owner_id: "OWNER_PLW",
    owner_display_name: "Poulsbo Pollywogs Owner",
    canonical_name: "Poulsbo Pollywogs",
    current_logo_path: "/assets/logos/pollywogs.svg",
    primary_color: "#22c55e",
    secondary_color: "#15803d",
    first_season: 2014,
    last_season: 2022,
    is_active: 0,
  },
];

export const GRAINS: { id: ResultGrain; label: string; description: string }[] = [
  { id: "player", label: "Player", description: "Aggregated by individual player" },
  { id: "franchise", label: "AFFL Franchise", description: "Aggregated by durable AFFL franchise" },
  { id: "team_season", label: "AFFL Team-Season", description: "Aggregated by specific historical team season" },
  { id: "nfl_team", label: "NFL Team", description: "Aggregated by pro football club" },
  { id: "position", label: "Position", description: "Aggregated by roster position (QB, RB, WR, TE, etc.)" },
  { id: "season", label: "Season", description: "Aggregated by NFL / AFFL competition year" },
  { id: "week", label: "Week", description: "Aggregated by specific matchup week" },
  { id: "game", label: "Game", description: "Aggregated by individual NFL game contest" },
  { id: "play", label: "Play", description: "Individual NFL play-level event grain" },
];

export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  affl_points: {
    id: "affl_points",
    name: "AFFL Fantasy Points",
    shortName: "AFFL Pts",
    category: "fantasy",
    description: "Standard non-PPR fantasy points scored in the AFFL.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? v.toFixed(1) : "—"),
  },
  bench_points: {
    id: "bench_points",
    name: "Bench Points Left",
    shortName: "Bench Pts",
    category: "fantasy",
    description: "Fantasy points scored while occupying an AFFL bench or inactive slot.",
    compatibleGrains: ["player", "franchise", "team_season", "position", "season", "week"],
    format: (v) => (v != null ? v.toFixed(1) : "—"),
  },
  xfp: {
    id: "xfp",
    name: "Expected Fantasy Points (xFP)",
    shortName: "xFP",
    category: "opportunity",
    description: "Expected standard non-PPR fantasy points based on down, distance, yardline, and air yards.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game", "play"],
    format: (v) => (v != null ? v.toFixed(1) : "—"),
  },
  fpoe: {
    id: "fpoe",
    name: "Fantasy Points Over Expected (FPOE)",
    shortName: "FPOE",
    category: "efficiency",
    description: "Actual AFFL fantasy points minus Expected Fantasy Points (xFP).",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? (v > 0 ? `+${v.toFixed(1)}` : v.toFixed(1)) : "—"),
  },
  custody_par: {
    id: "custody_par",
    name: "Custody Points Above Replacement (PAR)",
    shortName: "Custody PAR",
    category: "fantasy",
    description: "Fantasy points delivered above positional replacement level during active custody.",
    compatibleGrains: ["player", "franchise", "team_season", "position", "season"],
    format: (v) => (v != null ? (v > 0 ? `+${v.toFixed(1)}` : v.toFixed(1)) : "—"),
  },
  wopr: {
    id: "wopr",
    name: "Weighted Opportunity Rating (WOPR)",
    shortName: "WOPR",
    category: "opportunity",
    description: "1.5 * Target Share + 0.7 * Air Yards Share",
    compatibleGrains: ["player", "position", "season", "week"],
    format: (v) => (v != null ? v.toFixed(3) : "—"),
  },
  targets: {
    id: "targets",
    name: "Targets",
    shortName: "Tgt",
    category: "volume",
    description: "Total passing targets directed at player.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  receptions: {
    id: "receptions",
    name: "Receptions",
    shortName: "Rec",
    category: "volume",
    description: "Total completed passes caught.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rec_yds: {
    id: "rec_yds",
    name: "Receiving Yards",
    shortName: "Rec Yds",
    category: "volume",
    description: "Total receiving yardage gained.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rec_td: {
    id: "rec_td",
    name: "Receiving Touchdowns",
    shortName: "Rec TD",
    category: "volume",
    description: "Total receiving touchdowns scored.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rush_att: {
    id: "rush_att",
    name: "Rushing Attempts",
    shortName: "Carries",
    category: "volume",
    description: "Total rushing carries.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rush_yds: {
    id: "rush_yds",
    name: "Rushing Yards",
    shortName: "Rush Yds",
    category: "volume",
    description: "Total rushing yards gained.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  rush_td: {
    id: "rush_td",
    name: "Rushing Touchdowns",
    shortName: "Rush TD",
    category: "volume",
    description: "Total rushing touchdowns scored.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  pass_yds: {
    id: "pass_yds",
    name: "Passing Yards",
    shortName: "Pass Yds",
    category: "volume",
    description: "Total passing yards gained.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  pass_td: {
    id: "pass_td",
    name: "Passing Touchdowns",
    shortName: "Pass TD",
    category: "volume",
    description: "Total passing touchdowns thrown.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game"],
    format: (v) => (v != null ? Math.round(v).toString() : "—"),
  },
  epa: {
    id: "epa",
    name: "Expected Points Added (EPA)",
    shortName: "EPA",
    category: "efficiency",
    description: "Total Expected Points Added generated on plays involving the player.",
    compatibleGrains: ["player", "franchise", "team_season", "nfl_team", "position", "season", "week", "game", "play"],
    format: (v) => (v != null ? (v > 0 ? `+${v.toFixed(2)}` : v.toFixed(2)) : "—"),
  },
};

export const EXPLORE_PRESETS = [
  {
    id: "workload_left_on_bench",
    title: "Workload Left on the Bench",
    description: "Which workload spikes and scoring outbursts occurred while sitting on AFFL benches?",
    state: {
      scope: "rostered" as CustodyScope,
      grain: "player" as ResultGrain,
      metrics: ["bench_points", "affl_points", "xfp", "fpoe", "rush_yds", "rec_yds"],
      startSeason: 2018,
      endSeason: 2025,
      sortBy: "bench_points",
      sortDir: "desc" as const,
      limit: 50,
    },
  },
  {
    id: "talent_held_vs_started",
    title: "Talent Held vs. Talent Started",
    description: "Which franchises accumulated the most talent versus which ones maximized starting lineups?",
    state: {
      scope: "rostered" as CustodyScope,
      grain: "franchise" as ResultGrain,
      metrics: ["affl_points", "bench_points", "custody_par", "xfp", "fpoe"],
      startSeason: 2018,
      endSeason: 2025,
      sortBy: "affl_points",
      sortDir: "desc" as const,
      limit: 20,
    },
  },
  {
    id: "opportunity_vs_realized",
    title: "Opportunity Owned vs. Points Realized",
    description: "Comparison of expected standard non-PPR points (xFP) to actual AFFL points scored under custody.",
    state: {
      scope: "rostered" as CustodyScope,
      grain: "player" as ResultGrain,
      metrics: ["affl_points", "xfp", "fpoe", "targets", "rush_att"],
      startSeason: 2014,
      endSeason: 2025,
      sortBy: "xfp",
      sortDir: "desc" as const,
      limit: 50,
    },
  },
  {
    id: "redzone_by_franchise",
    title: "Red-Zone Opportunity by AFFL Franchise",
    description: "High-value goal-line and red-zone opportunities held across franchise histories.",
    state: {
      scope: "started" as CustodyScope,
      grain: "franchise" as ResultGrain,
      metrics: ["affl_points", "rush_td", "rec_td", "xfp", "fpoe"],
      startSeason: 2014,
      endSeason: 2025,
      sortBy: "rec_td",
      sortDir: "desc" as const,
      limit: 20,
    },
  },
  {
    id: "explosive_plays_under_custody",
    title: "Explosive Plays Under Custody",
    description: "Longest runs, deep passes, and game-breaking plays generated while in AFFL lineups.",
    state: {
      scope: "started" as CustodyScope,
      grain: "player" as ResultGrain,
      metrics: ["affl_points", "rec_yds", "rush_yds", "pass_yds", "epa"],
      startSeason: 2014,
      endSeason: 2025,
      sortBy: "affl_points",
      sortDir: "desc" as const,
      limit: 50,
    },
  },
];
